## < All Credits Goes To DarkBoy For Making This Bot > ##
## Main bot Config ##
mainprefix: '-' # Main Prefix 
token: 'NzU0MDA0MjcyODc3OTI4NTE5.X1ubMw.fyJM_WmEAnGiaz2tmqIJo4fy8F8' # Token of your bot
status: 'Bemo' # ur bot status
## Join Support Guild: https://discord.gg/6KYRXQC  ##
